### ISSUE TITLE
Remove old Joyent Go libraries in favor of triton-go

### ISSUE THREAD

**Issue by cheapRoc** [joyent/docker-machine-driver-triton#6]
There are several dependencies that need to be removed in favor of `triton-go`. 

Go engineers at Joyent are centralizing tools around our new SDK with the hope of expiring the old libraries. There are [examples](https://github.com/joyent/triton-go/tree/master/examples) of using `triton-go` in the repo and/or I can help with any part of it. If something doesn't map over please let us know.

- github.com/joyent/gocommon/client
- github.com/joyent/gosdc/cloudapi
- github.com/joyent/gosign/auth

Also, I would have done this myself but I'm not entirely certain of how this project is being distributed or how I can test it (?). A `README.md` would be nice.

**Comment by nimajalali** [comment]
@cheapRoc here's a README I started but haven't PR'd in yet.

https://gist.github.com/nimajalali/486b01998c55c50a6a8f199daaa4d849

**Comment by cheapRoc** [comment]
Looks good so far @nimajalali!

**Comment by cheapRoc** [comment]
While spending some time on this I found a few features we need to add to `triton-go`...

- Missing [`RebootMachine`](https://apidocs.joyent.com/cloudapi/#RebootMachine) support
- Missing support for the official `Ping` endpoint for testing the CloudAPI connections.
- This will be the fourth or fifth dependency for `triton-go` thus we **need** to start proper unit testing.
- [This gets fishy](https://github.com/joyent/docker-machine-driver-triton/blob/master/driver.go#L235) and we'll need to make sure we're handling this `image@version` format appropriately as`triton-go` does not support passing the Image Name or Image UUID through the same interface.

I'm already addressing these issues in the Triton Go SDK so it shouldn't be a problem to crank this out after support is upstreamed there. I'll update this task when that is complete later in the week.

**Comment by cheapRoc** [comment]
This is working and I'll have a PR up once I've tested remaining CLI flags and variables.

**Comment by cheapRoc** [comment]
I've opened joyent/triton-go [#50](https://github.com/joyent/triton-go/pull/50), [#51](https://github.com/joyent/triton-go/pull/51), and [#52](https://github.com/joyent/triton-go/pull/52) with the upstream functionality.

**Comment by cheapRoc** [comment]
Local testing worked out better than I expected. I'm using a local version of `triton-go` that includes all the latest functionality. I'm hesitant to open the PR yet as it's reliant on my upstream changes but once CR comes in I'll post it up.
